### ISSUE TITLE
Unable to display xml data when using hljs in detail.html

### ISSUE THREAD

**Issue by robpml** [marklogic/slush-marklogic-node#210]
I'm using some XML data and want to display the content when selected from a search. In previous iterations of slush-marklogic-node I made the following change to detail.html:

    <div class="row detail">
      
      <div hljs source="model.detail" language="xml"></div>
    </div>

and added hljs to app.js, but this does not work with the latest version of slush-marklogic-node I am using (0.2.0), with no output being displayed. The code I used is:

    <div class="panel-body">
        <div hljs source="ctrl.doc" language="xml"></div>
    </div>

but I did manage to get this working:

    <div class="panel-body">
        <pre>{{ctrl.doc}}</pre>
    </div>

**Comment by grtjn** [comment]
We are shipping hljs as a bower dependency by default, and it is commonly used as well..

**Comment by hunterwilliams** [comment]
Did the component properly add to index.html? Also any console errors? Not familiar with how to set this up to recreate the issue

**Comment by grtjn** [comment]
There was a console message deep inside highlightjs about some missing function. @robpml, can you recover that message, and add here?

**Comment by robpml** [comment]
sorry meant to include it originally - will recreate and update the case shortly..

**Comment by robpml** [comment]
Console output:

    TypeError: Cannot read property 'configure' of undefined
        at Object.$get (http://localhost:3000/bower_components/angular-highlightjs/build/angular-highlightjs.js:47:12)
        at Object.invoke (http://localhost:3000/bower_components/angular/angular.js:4476:17)
        at http://localhost:3000/bower_components/angular/angular.js:4293:37
        at getService (http://localhost:3000/bower_components/angular/angular.js:4435:39)
        at Object.invoke (http://localhost:3000/bower_components/angular/angular.js:4467:13)
        at extend.instance (http://localhost:3000/bower_components/angular/angular.js:9127:34)
        at nodeLinkFn (http://localhost:3000/bower_components/angular/angular.js:8239:36)
        at compositeLinkFn (http://localhost:3000/bower_components/angular/angular.js:7671:13)
        at compositeLinkFn (http://localhost:3000/bower_components/angular/angular.js:7675:13)
        at compositeLinkFn (http://localhost:3000/bower_components/angular/angular.js:7675:13) <ui-view class="ng-scope">

**Comment by robpml** [comment]
closed by mistake!

**Comment by hunterwilliams** [comment]
looking into it. relevant issue on their project -> https://github.com/pc035860/angular-highlightjs/issues/26 except it seems like it supposedly fixed

**Comment by hunterwilliams** [comment]
so confirmed that it was what the last comment on that issue is. basically our dependencies get out of order and highlights.js is being added after angular-highlights.js which is causing this error

**Comment by grtjn** [comment]
Ah, so bower overrides could indeed fix this. We could do both though, put angular-* at bottom, and add a bower override..
