### ISSUE TITLE
Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.

### ISSUE THREAD

**Issue by grtjn** [marklogic/slush-marklogic-node#213]
For the sake of posterity, I was seeing messages like below after some MacOS updates:

```
npm WARN engine get-stdin@5.0.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.26","npm":"2.13.1"})
npm WARN engine get-stdin@5.0.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.26","npm":"2.13.1"})
npm WARN engine get-stdin@5.0.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.26","npm":"2.13.1"})
npm WARN engine get-stdin@5.0.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.26","npm":"2.13.1"})
npm WARN engine get-stdin@5.0.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.26","npm":"2.13.1"})
 
> fsevents@0.3.8 install /Users/gjosten/Projects/github-grtjn/ml-github-search/github-search/node_modules/karma/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

|

Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.



-

Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.


gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 69
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/gjosten/Projects/github-grtjn/ml-github-search/github-search/node_modules/karma/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
```

If you see them too, just lauch Xcode manually, accept the license agreement, let it do its thing. To be sure, I just recreated the project I was creating. But that might be overkill..

**Comment by gon** [comment]
Indeed, no need to recreate a project or anything. The only thing you need to do is launch Xcode as mentioned by @grtjn!

**Comment by cdnbacon** [comment]
@grtjn thank you for putting this up, that solved the issue in no time.

**Comment by raoulus** [comment]
thanks, this helped me as well with another package..

**Comment by tomjwilliamson** [comment]
Thanks!

**Comment by TimoSolo** [comment]
or 

`sudo xcodebuild -license`

then 'agree' to it

**Comment by AngryITGuy** [comment]
Launching xCode and agreeing to new terms and conditions seems to be a solution. Although, my layman's observation is that a pending update to Xcode requires the user to re-approve the Xcode licence which in turns grants permission to the relevant directories.. Apple is almost like Microsoft..
