### ISSUE TITLE
Error: ENOENT, no such file or directory '.../ui/app/templates.js'

### ISSUE THREAD

**Issue by grtjn** [marklogic/slush-marklogic-node#365]
Running for instance `gulp serve-local` or `gulp build` results in:

```
[15:32:34] Starting 'templatecache'...
[15:32:34] Creating an AngularJS $templateCache
[15:32:34] Finished 'clean-fonts' after 735 ms
[15:32:34] Starting 'fonts'...
[15:32:34] Copying fonts
[15:32:35] Finished 'styles' after 1.48 s

fs.js:679
  return binding.lstat(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory '.../ui/app/templates.js'
    at Object.fs.lstatSync (fs.js:679:18)
    at DestroyableTransform.TransformStream [as _transform] (.../node_modules/gulp-angular-templatecache/node_modules/gulp-header/index.js:38:12)
    at DestroyableTransform.Transform._read (.../node_modules/gulp-angular-templatecache/node_modules/gulp-header/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (.../node_modules/gulp-angular-templatecache/node_modules/gulp-header/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (.../node_modules/gulp-angular-templatecache/node_modules/gulp-header/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (.../node_modules/gulp-angular-templatecache/node_modules/gulp-header/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (.../node_modules/gulp-angular-templatecache/node_modules/gulp-header/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:241:11)
    at write (.../node_modules/gulp-concat/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (.../node_modules/gulp-concat/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable .../node_modules/gulp-concat/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
```

Started happening as of this afternoon, with the release of `gulp-header@1.8.3`, which is included via `gulp-angular-templatecache`.

**Comment by grtjn** [comment]
Not sure if it only happens when using old NodeJS version (0.10.26 like me), but this seems to be the shortest route to fixing the issue:

- `npm uninstall gulp-angular-templatecache`
- edit `package.json`, and replace:
```
    "gulp-angular-templatecache": "^1.6.0",
```
with:
```
    "gulp-header": "1.8.2",
    "gulp-angular-templatecache": "^1.6.0",
```
- `npm install`
