### ISSUE TITLE
BrowserSync 2.8.4+ doesn't work with Nodejs v0.10

### ISSUE THREAD

**Issue by grtjn** [marklogic/slush-marklogic-node#433]
You'll see a message like:

```
$gulp wiredep

/Users/gjosten/Projects/marklogic_hsbc-tai/node_modules/browser-sync/node_modules/portscanner/node_modules/is-number-like/lib/index.js:2
const isNumber = require('lodash.isfinite')
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/gjosten/Projects/marklogic_hsbc-tai/node_modules/browser-sync/node_modules/portscanner/lib/portscanner.js:4:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by grtjn** [comment]
We should pin to `browser-sync#2.8.3` until we migrate to Nodejs v4..
